---
version: '3.7'
services:
  ## MySQL Docker Compose Config For Order Service
  order-service-mysql:
    container_name: order-service-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_order_service_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: orderservice
      MYSQL_ROOT_PASSWORD: Pancha100%

  ## MySQL Docker Compose Config For Inventory Service
  inventory-service-mysql:
    container_name: inventory-service-mysql
    image: mysql:5.7
    volumes:
      - ./DB_init:/docker-entrypoint-initdb.d
      - ./mysql_inventory_service_data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventoryservice
      MYSQL_USER: inventory
      MYSQL_PASSWORD: password
#      MYSQL_DATABASE: inventoryservice
#      MYSQL_ROOT_PASSWORD: Pancha100%

  ## Mongo Docker Compose Config For Product Service
#  mongo:
#    container_name: mongo
#    image: mongo:4.4.14-rc0-focal
#    restart: unless-stopped
#    ports:
#      - "27017:27017"
#    expose:
#      - "27017"
#    volumes:
#      - ./mongo-data:/data/db

  ## Keycloak Config with Mysql database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ## Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  ## Eureka Server
  discovery-server:
    image: bikashmunikar/discovery-server:latest
    container_name: discovery-server
    hostname: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  api-gateway:
    image: bikashmunikar/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8181:8080"
    expose:
      - "8181"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - zipkin
      - discovery-server
      - keycloak

  ## Product-Service Docker Compose Config
#  product-service:
#    container_name: product-service
#    image: bikashmunikar/product-service:latest
#    pull_policy: always
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - mongo
#      - discovery-server
#      - api-gateway
#    links:
#      - discovery-server

  ## Order-Service Docker Compose Config
  order-service:
    container_name: order-service
    image: bikashmunikar/order-service:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_HOST: order-service-mysql
      MYSQL_USER: bikash
      MYSQL_PASSWORD: Pancha100%
      MYSQL_PORT: 3306
    depends_on:
      - order-service-mysql
      - broker
      - zipkin
      - discovery-server
      - api-gateway

  ## Inventory-Service Docker Compose Config
  inventory-service:
    container_name: inventory-service
    image: bikashmunikar/inventory-service:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_HOST: inventory-service-mysql
      MYSQL_USER: inventory
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    depends_on:
      - inventory-service-mysql
      - discovery-server
      - api-gateway
      - zipkin

  ## Notification-Service Docker Compose Config
  notification-service:
    container_name: notification-service
    image: bikashmunikar/notification-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - broker
      - discovery-server
      - api-gateway

  ## Prometheus
#  prometheus:
#    image: prom/prometheus:v2.37.1
#    container_name: prometheus
#    restart: always
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    depends_on:
#      - product-service
#      - inventory-service
#      - order-service
#      - notification-service
#
#  grafana:
#    image: grafana/grafana-oss:8.5.2
#    container_name: grafana
#    restart: always
#    ports:
#      - "3000:3000"
#    links:
#      - prometheus:prometheus
#    volumes:
#      - ./grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=password